Create user classes (person, teacher, student)
Bavon101/school_library pull request #1
Opened 2022-05-09 18:59 UTC by Bavon101

Hello, as per this PR I managed to achieve the following:

### Project requirements

- [ ]  Create class `Person` with  the following:
  - Instance vars: `@id`, `@name`, and `@age`.
  - Constructor with `name`,  `age`, and `parent_permission` as parameter. `name` and `parent_permission` are optional and have default values of `"Unknown"` and `true`.
  - Getters for `@id`, `@name`, and `@age`.
  - Setters for `@name` and `@age`.
  - Private method `is_of_age?` that returns `true` if `@age` is greater or equal to 18 and `false` otherwise.
  - Public method `can_use_services?` that returns `true` if person is of age or if they have permission from parents.
- [ ] Create class `Student` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@classroom` and a parameter for it.
  - Method `play_hooky` that returns `"¯\(ツ)/¯"`.
- [ ]  Create class `Teacher` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@specialization` and a parameter for it.
  - Override `can_use_services?` so it always returns `true`.
- [ ]  Each class should be saved in a separate file.

2022-05-09 19:12 UTC, mikethreels requested changes
Hi Bavon, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-09 19:12 UTC, mikethreels commented on person.rb
> +  end
- [ ] all methods below the `private` keyword will be private, in this case, can_use_services, will also be private. please change this so the method is public instead.
- [ ] it should depend on the parent's permission if the user can use the services if the age is below 18, please implement this as well.

2022-05-09 19:12 UTC, mikethreels commented on person.rb
> +    @id = id
- [ ] I would advise you to use a random number for the @id, it will not be needed to include it in the arguments either.

2022-05-09 19:12 UTC, mikethreels commented on student.rb
> +    @classroom = classroom
- [ ] to make this work please pass all the arguments from the initialize method in the Person class in this initialize method as well and add them to the super as arguments as well.

2022-05-09 19:12 UTC, mikethreels commented on teacher.rb
> +    super()
- [ ] to make this work please pass all the arguments from the initialize method in the Person class in this initialize method as well and add them to the super as arguments as well.

2022-05-09 19:12 UTC, mikethreels commented on README.md
> +
- [ ] please make sure to use [the template](https://github.com/microverseinc/readme-template) for the readme file provided by Microverse, including the links (for example to the MIT license). keep in mind that all sections of the template are mandatory except for the "Live Demo", "Run Tests" and "Deployment" sections, these are only mandatory if the specific project you're working on requires it.

2022-05-10 06:26 UTC, Meltrust requested changes
Hi @Bavon101,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 06:26 UTC, Meltrust commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] As requested by the previous reviewer, all links should work.  This needs to point to your LICENSE file.  Kindly make it so.

That way, your project will be well documented 💪

2022-05-10 06:33 UTC, Meltrust approved these changes
Hi @Bavon101,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for correcting the link to the license file, as requested in the previous review 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 06:34 UTC, merged